move kernel\help.c kernel\commands\
move kernel\touch.c kernel\commands\
move kernel\ls.c kernel\commands\
move kernel\rm.c kernel\commands\
move kernel\mkdir.c kernel\commands\
move kernel\rmdir.c kernel\commands\
move kernel\cp.c kernel\commands\
move kernel\mv.c kernel\commands\
move kernel\grep.c kernel\commands\
move kernel\head.c kernel\commands\
move kernel\tail.c kernel\commands\
move kernel\more.c kernel\commands\
move kernel\tree.c kernel\commands\
move kernel\edit.c kernel\commands\
move kernel\view.c kernel\commands\
move kernel\clear.c kernel\commands\
move kernel\ps.c kernel\commands\
move kernel\free.c kernel\commands\
move kernel\kill.c kernel\commands\
move kernel\sleep.c kernel\commands\
move kernel\wait.c kernel\commands\
move kernel\systemctl.c kernel\commands\
move kernel\ramfs_tools.c kernel\commands\
move kernel\cat.c kernel\commands\
move kernel\calculator_app.c kernel\apps\
move kernel\myra_app.c kernel\apps\
move kernel\terminal_app.c kernel\apps\
move kernel\files_app.c kernel\apps\
move kernel\keyboard_tester_app.c kernel\apps\
move kernel\v_edit.c kernel\apps\editor_app.c
