move /Y kernel\help.c kernel\commands\
move /Y kernel\touch.c kernel\commands\
move /Y kernel\ls.c kernel\commands\
move /Y kernel\rm.c kernel\commands\
move /Y kernel\mkdir.c kernel\commands\
move /Y kernel\rmdir.c kernel\commands\
move /Y kernel\cp.c kernel\commands\
move /Y kernel\mv.c kernel\commands\
move /Y kernel\grep.c kernel\commands\
move /Y kernel\head.c kernel\commands\
move /Y kernel\tail.c kernel\commands\
move /Y kernel\more.c kernel\commands\
move /Y kernel\tree.c kernel\commands\
move /Y kernel\edit.c kernel\commands\
move /Y kernel\view.c kernel\commands\
move /Y kernel\clear.c kernel\commands\
move /Y kernel\ps.c kernel\commands\
move /Y kernel\free.c kernel\commands\
move /Y kernel\kill.c kernel\commands\
move /Y kernel\sleep.c kernel\commands\
move /Y kernel\wait.c kernel\commands\
move /Y kernel\systemctl.c kernel\commands\
move /Y kernel\ramfs_tools.c kernel\commands\
move /Y kernel\cat.c kernel\commands\
move /Y kernel\calculator_app.c kernel\apps\
move /Y kernel\myra_app.c kernel\apps\
move /Y kernel\terminal_app.c kernel\apps\
move /Y kernel\files_app.c kernel\apps\
move /Y kernel\keyboard_tester_app.c kernel\apps\
move /Y kernel\v_edit.c kernel\apps\editor_app.c
move /Y kernel\echo.c kernel\commands\
